### ISSUE TITLE
如何添加自定义Service路由

### ISSUE THREAD

**Issue by zchunhai** [secretflow/kuscia#196]
比如在autonomy模式下，Alice和Bob的管理平台之间需要进行通信。

这样的通信是否可以复用kuscia的ClusterDomainRoute机制，Service该如何定义呢？

**Comment by gshilei** [comment]
通过复用kuscia提供的网络打平功能，可以在alice和bob 中自定义service，进行请求转发。
下面是Alice和Bob的管理平台之间需要进行通信示例：
- 在Alice侧，手动创建一个ExternalName类型的Service, 其中ExternalName设置为Alice平台的地址，例如:
```
apiVersion: v1
kind: Service
metadata:
  name: alice-pad
  namespace: alice
spec:
  # 10.88.0.2为alice平台服务的地址
  externalName: 10.88.0.2
  ports:
  - name: cluster
    port: 10010
  type: ExternalName
status:
  loadBalancer: {}
```
- 在Bob侧，手动创建一个ExternalName类型的Service, 其中ExternalName设置为Bob的地址，例如:
```
apiVersion: v1
kind: Service
metadata:
  name: bob-pad
  namespace: bob
spec:
  # 10.88.0.3为alice平台服务的地址
  externalName: 10.88.0.3
  ports:
  - name: cluster
    port: 10010
  type: ExternalName
status:
  loadBalancer: {}
```

下面是Alice访问Bob侧平台的方法，反之类似：
- 若在Alice Docker容器内，直接访问Bob平台的方式： `curl -v http://bob-pad.bob.svc`
- 若在Alice Docker容器外，那么需要把Alice节点的80端口暴露到宿主机上，然后通过`curl -v http://127.0.0.1:{暴露在宿主机上的端口} -H "host:bob-pad.bob.svc"`
