### ISSUE TITLE
KusciaTask 任务支持全链路时间观测开发任务

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#29]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：KusciaTask 任务支持全链路时间观测开发任务
- 技术方向：可观测性
- 任务难度：进阶🌟🌟

## 详细要求：
- 功能性：
  - KusciaTask Controller 支持创建的任务 Pod 资源时间观测，包括 Pod 调度到节点上的时间戳/节点拉起 Pod 容器的时间戳
  - KusciaTask Controller 支持创建的任务 Service 资源时间观测，包括节点 Gateway 处理完 Service(Endpoints) 的时间戳
- 正确性：代码开发完成后，基于最新的代码构建镜像，然后使用构建的镜像部署 Kuscia，然后下发 KusciaJob 作业，观察 KusciaJob 作业下的 KusciaTask 任务所包含的观测到的 Pod 资源时间戳和 Service 资源时间戳是否正确
- 代码规范：https://github.com/uber-go/guide/blob/master/style.md
- 提交说明：
  - 关联该 ISSUE 并先准备详细的设计方案文档，请在 ISSUE 下评论提交方案，经过我们确认后进行开发。
  - 功能开发完成后，关联该 ISSUE 并提交代码至 https://github.com/secretflow/kuscia
- 提示：
  - 在 KusciaTask CRD 中新增 Pod 和 Service 的观测性时间指标
  - 在修改完 kusciatask_types.go 后，在 Kuscia 根目录下执行以下命令可以更新 K8s Clients 代码和更新后的 CRD
    - make gen-clientset
    - make manifests
  - 基于最新的代码构建镜像
    - make image

## 能力要求
- 熟悉 Golang、Protobuf
- 熟悉 K8s Controller 机制
- 熟悉 K8s CRD 概念

## 操作说明
- 参考内容：
  - 在 KusciaTask 的 Status 字段下新增 Pod 和 Service 时间观测性字段，请参考[KusciaTask 类型定义](https://github.com/secretflow/kuscia/blob/main/crds/v1alpha1/kuscia.secretflow_kusciatasks.yaml)
  - [Gateway处理 Service(Endpoints) 相关代码](https://github.com/secretflow/kuscia/blob/main/pkg/gateway/controller/endpoints.go)
  - [构建 Kuscia Image](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn)

**Comment by hdkoutann** [comment]
hdkoutann Give it to me

**Comment by hdkoutann** [comment]
1. 概要分析
    1. Pod资源时间观测
        
        包括两个内容，节点创建pod时间戳和pod拉起成功时间戳
        
        KusciaTask的TaskStatus定义里面已经有podStatuses内容，podStatuses包含所有task part所需要创建的pod，在当前版本的podStatuses中添加两个字段：
        
        1. podCreateTime(pod创建时间)
        2. podStartupTime(pod启动时间)
        
        ```yaml
        podStatuses:
            alice/secretflow-task-psi-0:
              podCreateTime: "2023-06-26T03:46:58Z"
              podStartupTime: "2023-06-26T03:46:58Z"
        ```
        
    2. Service(Endpoints)资源时间观测
        
        当前KusciaTask的CRD定义没有service相关内容，需要添加字段。
        
        在podStatuses下新建envoyServices字段，以及处理时间戳decorateTime
        
        ```yaml
        podStatuses:
            alice/secretflow-task-psi-0:
              podCreateTime: "2023-06-26T03:46:58Z"
              podStartupTime: "2023-06-26T03:46:58Z"
        			envoyServices:
        				- serviceName: task-template-psi-0-global
        					decorateTime: "2023-06-26T03:46:58Z"
        ```
        
2. 详细方案
    1. pod创建和拉起时间添加
        
        KusciaTask处理逻辑中监听pod状态并更新逻辑，在pkg\controllers\kusciatask\handler\running_handler.go添加判断，判断pod状态
        
        当pod在pending状态，更新podStatuses中podCreateTime字段
        
        当pod在running状态，更新podStatuses中podStartupTime字段；
        
        pod挂掉自动重启情况应该也可以覆盖到。
        
    2. envoy完成时间添加
        
        envoy的后置处理逻辑在pkg\gateway\controller\endpoints.go中，监听Service变更事件后创建envoy节点。
        
        service的变更事件中可以获取到kuscia的Service，通过service的OwnerReferences获取到pod，通过pod的OwnerReferences可以获取到KusciaTask，通过获取到的kusciaTask更新envoServices的decorateTime字段；

**Comment by hdkoutann** [comment]
这样设计实现是否可行呀

**Comment by gshilei** [comment]
@hdkoutann 感谢你的积极参与，针对你上面设计方案，有以下建议：

1. Pod资源时间观测

- podStartupTime 可以细粒度地拆分成：scheduledTime/readyTime；podStatuses结构如下：
```
podStatuses:
   alice/secretflow-task-psi-0:
     ...
     createdTime: "2023-06-26T03:46:58Z"       -> 对应pod资源的 metadata.creationTimestamp
     scheduledTime: "2023-06-26T03:47:01Z"   -> 对应pod资源status.conditions[PodScheduled].lastTransitionTime
     readyTime: "2023-06-26T03:47:05Z"           -> 对应pod资源status.conditions[Ready].lastTransitionTime
```
2. Service(Endpoints)资源时间观测

- 新增serviceStatuses字段，存放service的时间信息
- service包含2个字段：createdTime 和 readyTime
- readyTime：当gateway处理watch的service和endpoint时，最后会调用AddEnvoyCluster。在add envoy cluster成功之后，gateway 给对应service的annotation新增字段kuscia.secretflow/ready-time；kusciaTask Controller 通过List-Watch机制监听到该service有变化之后，更新 KusciaTask 中的serviceStatuses字段。

```
podStatuses:
  ...
serviceStatuses:
  alice/secretflow-task-xxx-single-psi-0-spu:
    createdTime: "2023-06-26T03:46:58Z"    -> 对应service资源的 metadata.creationTimestamp
    readyTime: "2023-06-26T03:46:59Z"        -> 对应service资源的 annotations kuscia.secretflow/ready-time:  2023-06-26T03:46:59Z
  alice/secretflow-task-xxx-single-psi-0-global:
    createdTime: "2023-06-26T03:46:58Z"
    readyTime: "2023-06-26T03:46:59Z" 
  bob/secretflow-task-xxx-single-psi-0-spu:
    createdTime: "2023-06-26T03:46:58Z"
    readyTime: "2023-06-26T03:46:59Z" 
  bob/secretflow-task-xxx-single-psi-0-global:
    createdTime: "2023-06-26T03:46:58Z"
    readyTime: "2023-06-26T03:46:59Z" 
```

**Comment by koutann** [comment]
感谢回复，抱歉才回复@gshilei
serviceStatuses和podStatuses一样单独存储便于后续扩展，在endpoint里添加service自定义时间参数，在KusciaTask通过Kist-Watch获取变更进行处理做到解耦，你指出的改进很有道理，方案可行，我准备按这个方案着手开发了。
计划本周开发完，下周验证后提交pr

**Comment by hdkoutann** [comment]
在mac上make image速度非常非常慢，基本make不出来，有什么办法可以提速么@gshilei

**Comment by gshilei** [comment]
能看一下，在Make的过程中，哪一步比较慢吗？

**Comment by hdkoutann** [comment]
![1691989496842](https://github.com/secretflow/kuscia/assets/129133814/eadb93ea-4851-4ef4-bdf5-12a4f91baef0)
依赖的kuscia-envoy和kuscia-deps下载很慢

**Comment by hdkoutann** [comment]
搭了下centos虚拟机上跑也不行，是不是机器配置不行还是网络配置有问题？

**Comment by gshilei** [comment]
从上面看，构建Kuscia镜像时依赖的两个基础镜像：secretflow/kuscia-envoy:0.2.0b0 和 secretflow/kuscia-deps:0.1.0b0下载比较慢，可以尝试下配个加速器 https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6 看是否有效果。

在构建Kuscia镜像之前，可以手动先把两个镜像下载到本地

**Comment by hdkoutann** [comment]
https://gist.github.com/y0ngb1n/7e8f16af3242c7815e7ca2f0833d3ea6 这个打不开呀

**Comment by gshilei** [comment]
Hi @hdkoutann , 使用下面方式，下载依赖的镜像
docker pull secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia-deps:0.1.0b0
docker tag secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia-deps:0.1.0b0 docker.io/secretflow/kuscia-deps:0.1.0b0

docker pull secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia-envoy:0.2.0b0
docker tag secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia-envoy:0.2.0b0 docker.io/secretflow/kuscia-envoy:0.2.0b0

**Comment by gshilei** [comment]
Hi @hdkoutann, 抱歉现在才回复，针对podStatuses下的时间需要再调整下，以便更细粒度的展示每个阶段的时间点。建议如下：

下面4个时间字段，会先定义出来。除了scheduleTime字段本期留空外，其他字段根据实际值填写。

```
podStatuses:
  alice/secretflow-task-psi-0:
    ...
    createTime: "2023-06-26T03:46:58Z"        -> 1. pod创建时间，对应pod.metadata.creationTimestamp
    scheduleTime: "2023-06-26T03:40:00Z"      -> 2. pod调度时间，本期不填
    startTime: "2023-06-26T03:47:02Z"         -> 3. pod被agent接受时间，对应pod.status.startTime
    readyTime: "2023-06-26T03:47:05Z"         -> 4. pod被agent拉起时间，对应pod.status.conditions[Ready].lastTransitionTime
```
