### ISSUE TITLE
Kusica K3S API 白名单

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#32]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：Kuscia K3S API 白名单
- 技术方向：网络授权
- 任务难度：进阶🌟🌟

## 详细要求
- 功能性
  - 支持以配置文件的形式设置 K3S API 白名单
  - 配置文件为 yaml 格式
- 准确性：
  - Master K3S 只允许白名单中的API被访问
- 提交说明：关联该 ISSUE 并提交代码至 https://github.com/secretflow/kuscia/blob/main/pkg/gateway/clusters/master.go和https://github.com/secretflow/kuscia/tree/main/etc/conf/domainroute
- 代码规范：https://github.com/uber-go/guide/blob/master/style.md

## 能力要求
- 了解基本 git 操作
- 对 Kuscia 有一定了解
- 了解 K8S 或 K3S 
- 熟悉 Golang

## 操作说明
- 请将测试结果的截图贴在 ISSUE 下，包括请求白名单列表之中的API和之外的 API 的响应截图。
- Kuscia 开发参考：[Kuscia 开发指南](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn)

**Comment by rayshaw001** [comment]
rayshaw001 git it to me

**Comment by rayshaw001** [comment]
### 基本思路
##### 对满足如下条件的VirtualHost单独设置访问（Route）白名单限制：
1. cluster = master
2. VirtualHost = internalVirtualHost
3. domain = apiserver.master.srv

### 存在的疑问：
1. 从节点和主节点访问K3S Master API都要设置访问白名单？
2. 同一个VirtualHost下，似乎不能将特定的Route和Domain绑定，这是不是意味要新增一个新的VirtualHost来实现这个功能？

**Comment by Eiji911** [comment]
我们只是要把这里的硬编码改成从配置文件中读取。
![image](https://github.com/secretflow/kuscia/assets/137666922/74961103-8612-4572-9e6f-b2f41a55c18c)

**Comment by Eiji911** [comment]
A1：只要在主节点上设置白名单就可以了。

**Comment by rayshaw001** [comment]
> 我们只是要把这里的硬编码改成从配置文件中读取。 ![image](https://user-images.githubusercontent.com/137666922/260342546-74961103-8612-4572-9e6f-b2f41a55c18c.png)


**已更新为从配置文件中读取正则表达式：https://github.com/secretflow/kuscia/pull/70/files**


但经过测试，不在名单里的资源仍可以正常访问
测试配置文件如下：
```yml
whitelist:
  apis:
    # - /(api(s)?(/[0-9A-Za-z_.-]+)?/v1(alpha1)?/namespaces/[0-9A-Za-z_.-]+/(pods|gateways|domainroutes|endpoints|services|events|configmaps|leases|taskresources|secrets|domaindatas|domaindatagrants|domaindatasources)(/[0-9A-Za-z_.-]+(/status$)?)?)
    - /(api(s)?(/[0-9A-Za-z_.-]+)?/v1(alpha1)?/namespaces/[0-9A-Za-z_.-]+/(gateways|domainroutes|endpoints|services|events|configmaps|leases|taskresources|secrets|domaindatas|domaindatagrants|domaindatasources)(/[0-9A-Za-z_.-]+(/status$)?)?)
    - /api/v1/namespaces/[0-9A-Za-z_.-]+
    - /api/v1/nodes(/.*)?
```

测试命令如下：

```shell
# 脚本来源：scripts/deploy/create_token.sh
DOMAIN_ID=bob
TOKEN=`kubectl create token $DOMAIN_ID --duration 87600h -n $DOMAIN_ID`
curl -k https://127.0.0.1:6443/api/v1/namespaces/${DOMAIN_ID}/pods -H"Authorization: Bearer ${TOKEN}"
```

测试结果如下，和在白名单中的结果一致:
```json
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "5991"
  },
  "items": []
}
```
