### ISSUE TITLE
如何在kuscia 容器内，查看kuscia真正的配置信息？

### ISSUE THREAD

**Issue by gxcuit** [secretflow/kuscia#324]
[文档](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/deployment/kuscia_config_cn#id1)中有写kuscia的配置文件在这里

我想问一下：假设我已经部署了一个kuscia的容器，怎样看到kuscia 所有的配置项， i.e. 有类似与kubectl 的方式能查看吗？/home/kuscia/etc/conf/kuscia.yaml, 只有部分的信息 (例如没有protocol)

此外，对于已经部署的kuscia容器，如果想要调整配置信息，如何操作，只需要改/home/kuscia/etc/conf/kuscia.yaml 就可以吗？是否需要执行命令使其生效？

Thanks！！！
---- 

```
mode: autonomy
domainID: alice
domainKeyData: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNkFadkNXc0ZqZEUrSXBPblhuaXBiSk9DZHZKRk1Wd2ZnK2pidnZySjVldUI5NjZBCnp3WkU4QmY4QVhhR2hYK3JjbFFIUmpXc000ei9HNWRyY1d1bUFDY2o1U1FKMjlBVzJxdFFFMjRIZEtlZlY4cTEKNzNackdSaHlhUk9aMlJuaHhmK0tLMGRISzBXUy85ZXlOaUN2T0N0WFdEakVIbXlHMnJ5elpqUnpnTlVTc3ZlWgpsVGNDTC9OQ090TzRxdzFlZ3Q0RXNJSXdXRjA0UklJZURKSGtQSE5ETTBpRHBNSkt1azNBZlR5blRFb2F6RmdyCkNoUTlpMlFrT2xYOEJZaWM0UVNrb0xIMy9CeVdSay9HbzI1bExuVjZka3N4MzhNeHlteGl0dUQyRGc4M29pUjUKVm12ZjcxUWU0bnJnMTNOSDRTVzdYZm5EdHlsZll1WE9uVitqU1FJREFRQUJBb0lCQUgvQkV5QlhhaDUxQ01aWApFSC9HNWxxZk9lV3ViZ1RJbVoyeStGUEdtS1pkTHhtbVhzd2V3cFNFVUVDcDkxWElQeWxiTlFvbWdXTjlEZll1ClFIMlo3VFFHV1JCUThKQzBtZkRiQk9NOTRTTU5MSUpWWGltMHhURnpNWVBEeENFeXpBcU9NcEN6MVc3eEJ3aVIKeGxGaFc3a012RElhUjNvTS9ZK3crUUtjZk1DQkJRejlvTG9Zb2UvTDV3UkJNR3JLTmljTUZ4bDNCQVVydHowdgovSHZrQ1BPWW1EWVE4UTBXanp2c012NVdTNzlwSzZ4UFBIRU84VERDTkR3cWpYU0oyeUlvb2dSb2R3M2NQRjNSCmp2cUVhQ3FIQjIvRkYya25Qa0t2ZnZPdUpmajJQeXRVTEtqR0RlN0tDR0t6TE55VXlhTUZFS1FvampQNEFtUkcKVzZNUDZsRUNnWUVBL1ZCMVluQ0tDMGMxS1N3clJqdXdLT2F1K2FVNHhFMllkdGRNN084bURGQ0ZkNmM3VFNZQwpwbm4zaUNPc3kzUkVPbXgvUTJZc2F3dlpIbzR1aWFKTjU0WTRtME5xQXFkT1N2ZU9QNE9qc2ZxemY0NzhnVk9PCmU4Znl3TEgwNHQ1Z2RCRURtalJlUm80VlVkeHhrV3o1cVV4Z1VGRkZDOU5vT0R3ajZaT0syWDBDZ1lFQTZud3gKU1BIcHRwaUJxWStwRHpoMDFZUGdjMlh3RHRzM2loZGRTcUNLNnZqNmgrWE5JUEUyTnVjTFNrSmg4MWVxVHhlNgpCbDBreUVjQld5dk1IZUVDbUNkNGtmZEwxZTNvUEpSUkU1bGRlR3MwdEFoRmFLL3FEZGh2aUhpZmxnVUpjMEV4Cm5VaVZxZm1FMTU0TEVwNTFPOHoxNnVqaWxuLzRoMm1xaFBhdCtyMENnWUVBK0VBNHVmOTJtZlR3R1dpTEJHcU0KaXBrQTAvSGkveWJZaTJjV29ZRUJ0Y0hYKzFwdDJINnV6RDN0bzRMcTNmMFV2SGtHQTZTSFZXVW9KRFROVU44NgpIL00vV0pJcHUyNEJZYURZekZBVFJlSmV0VjBKQXlsREV2WHlabnhBZFhIZjd2K1pteTlGVVRuL2xObEloMi9ZCkFOMno2aUtyV3hxVkliOTJwbnVNOFBVQ2dZRUFqbWFOcDdjQ01CbTk1TE9SLytSUlQ3bWUvWFhTcTdNRnI1OHcKMExsZXBBUkFZWGQxYzZRSlFKNWZoT0Y3aXNTYWNSMy9vdzI5NE1MK1Y5ZnBSZHY0TDE4Sklkd0UrZzVaRXpFZgphNytmdkJtZkVCWlYwSlhFbGxQeXAvWlpORW9xeXd1MGpjZ2UyL0xrY2UxUTNDWFBIRm9Fbm54LzN0WW9vRlBUCmNwdzhYQ0VDZ1lFQXFCVWV3RTUyYjQ5MTFyTHVYY3RHYTFGREFTUThjZTlrbWVyNkRYempBK3dTQW9OY1BXREcKTzFpUDZqTk9heENEeGpHdE9Vb0R1MUVzb3VtMVRjSWRtTEVtOGFrM0dNNEx0QzJ6OGhNWXgreVZRSTJIUGppbgpQVXQrbGtRQ1VBeVdETEh6MkZxNjJzZSttRVFYbUhGc3kxTkx6eTZkZUhlNC9sbm4yb1Q1QytBPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
logLevel: INFO
runtime: runc
runk:
  namespace: ""
  dnsServers: []
  kubeconfigFile: ""
capacity:
  cpu: ""
  memory: ""
  pods: ""
  storage: ""
image:
  pullPolicy: ""
  defaultRegistry: ""
  registries: []
datastoreEndpoint: ""

```
