### ISSUE TITLE
创建 SecretFlow Serving，状态一直Progressing

### ISSUE THREAD

**Issue by Sept98** [secretflow/kuscia#340]
### Issue Type

Others

### Search for existing issues similar to yours

Yes

### Kuscia Version

kuscia: latest

### Link to Relevant Documentation

https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.6.0b0/tutorial/run_sf_serving_with_api_cn#secretflow-serving

### Question Details

```shell
kuscia训练并正常导出了模型，根据https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.6.0b0/tutorial/run_sf_serving_with_api_cn#secretflow-serving进行创建 SecretFlow Serving，batchQuery状态一直是Progressing，后台pods文件夹下的log看一直有GetModelInfo failed, msg:[E1010]HTTP/1.1 404 Not Found, may need retry的waring，请问是为什么呀
```

**Comment by Sept98** [comment]
具体日志：

**Comment by Sept98** [comment]
create的参数：{
    "serving_id": "zze-serving",
    "serving_input_config": "{\"partyConfigs\": {\"node1\": {\"serverConfig\": {\"featureMapping\": {\"x1\": \"x1\", \"x2\": \"x2\"}}, \"modelConfig\": {\"modelId\": \"model-export\", \"basePath\": \"/home/kuscia/var/storage/data\", \"sourcePath\": \"/home/kuscia/var/storage/data/model.tar\", \"sourceType\": \"ST_FILE\"}, \"featureSourceConfig\": {\"mockOpts\": {}}, \"channel_desc\": {\"protocol\": \"http\"}}, \"node2\": {\"serverConfig\": {\"featureMapping\": {\"x3\": \"x3\"}}, \"modelConfig\": {\"modelId\": \"model-export\", \"basePath\": \"/home/kuscia/var/storage/data\", \"sourcePath\": \"/home/kuscia/var/storage/data/model.tar\", \"sourceType\": \"ST_FILE\"}, \"featureSourceConfig\": {\"mockOpts\": {}}, \"channel_desc\": {\"protocol\": \"http\"}}}}",
    "initiator": "node1",
    "parties": [
        {
            "domain_id": "node1",
            "app_image": "secretflow-serving-image",
            "role": "",
            "replicas": 1,
            "resources": []
        },
        {
            "domain_id": "node2",
            "app_image": "secretflow-serving-image",
            "role": "",
            "replicas": 1,
            "resources": []
        }
    ]
}

**Comment by Sept98** [comment]
启serving服务是哪一步呢？我现在是走到这一步
![图片](https://github.com/secretflow/kuscia/assets/58546241/13c57ed4-dd4b-41ca-a6c5-bd0fb9dbabfa)

**Comment by Sept98** [comment]
然后下一步进行查询serving状态：
![图片](https://github.com/secretflow/kuscia/assets/58546241/d68899e5-f4ea-4670-b432-8972046ab9d6)
出现的状态一直Progressing

**Comment by zimu-yuxi** [comment]
确认下你的模型包是tar包还是tar.gz包以及sourcepath路径是否准确

**Comment by Sept98** [comment]
应该是对的吧，我看日志里有
![图片](https://github.com/secretflow/kuscia/assets/58546241/e4a556e2-3ab7-409a-9cfd-4d7ac34e034b)
并且两个节点对应文件夹下model也都复制到{basePath}/{modelId}下了
![图片](https://github.com/secretflow/kuscia/assets/58546241/0d333cf7-930c-4718-8ec4-c1a38ae2548b)
如果sourcepath不正确应该复制不过去吧

**Comment by Sept98** [comment]
模型是tar包，当时保存的时候命名直接是tar，这个会有影响么

**Comment by zimu-yuxi** [comment]
[这里](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/tutorial/run_sf_serving_with_api_cn#secretflow-serving)，双方节点都有操作吗？

**Comment by Sept98** [comment]
创建应用模板都有，是p2p模式，
![图片](https://github.com/secretflow/kuscia/assets/58546241/a1834de2-ba36-4572-b4aa-2da266e9edb7)
![图片](https://github.com/secretflow/kuscia/assets/58546241/c7009d53-02ad-4967-bfe5-7c7d389dae43)

请问后面这一步也需要双方都操作么？
![图片](https://github.com/secretflow/kuscia/assets/58546241/fcc51158-1ee5-4117-be87-ce34150984a7)

**Comment by huocun-ant** [comment]
能发一下serving的app_image配置吗, 参考https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/reference/concepts/appimage_cn#id2

**Comment by Sept98** [comment]
改了个镜像，哦这里还需要有配置和create里面对应么：
```yaml
apiVersion: kuscia.secretflow/v1alpha1
kind: AppImage
metadata:
  name: secretflow-serving-image
spec:
  configTemplates:
    serving-config.conf: |
      {
        "serving_id": "{{.SERVING_ID}}",
        "input_config": "{{.INPUT_CONFIG}}",
        "cluster_def": "{{.CLUSTER_DEFINE}}",
        "allocated_ports": "{{.ALLOCATED_PORTS}}"
      }
  deployTemplates:
  - name: secretflow
    replicas: 1
    spec:
      containers:
      - command:
        - sh
        - -c
        - ./secretflow_serving --flagfile=conf/gflags.conf --config_mode=kuscia --serving_config_file=/etc/kuscia/serving-config.conf
        configVolumeMounts:
        - mountPath: /etc/kuscia/serving-config.conf
          subPath: serving-config.conf
        name: secretflow
        ports:
        - name: service
          port: 53508
          protocol: HTTP
          scope: Domain
        - name: communication
          port: 53509
          protocol: HTTP
          scope: Cluster
        - name: internal
          port: 53510
          protocol: HTTP
          scope: Domain
        - name: brpc-builtin
          port: 53511
          protocol: HTTP
          scope: Domain
        readinessProbe:
          httpGet:
            path: /health
            port: 53511
        livenessProbe:
          httpGet:
            path: /health
            port: 53511
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: 53511
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        workingDir: /root/sf_serving
  image:
    name: secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/serving-anolis8
    tag: 0.3.1b0
```

**Comment by huocun-ant** [comment]
kuscia中把一些端口改成了自动分配，app_image的写法需要变一下，改成这样试试呢

``` yaml
apiVersion: kuscia.secretflow/v1alpha1
kind: AppImage
metadata:
  name: secretflow-serving-image
spec:
  configTemplates:
    serving-config.conf: |
      {
        "serving_id": "{{.SERVING_ID}}",
        "input_config": "{{.INPUT_CONFIG}}",
        "cluster_def": "{{.CLUSTER_DEFINE}}",
        "allocated_ports": "{{.ALLOCATED_PORTS}}"
      }
  deployTemplates:
  - name: secretflow
    replicas: 1
    spec:
      containers:
      - command:
        - sh
        - -c
        - ./secretflow_serving --flagfile=conf/gflags.conf --config_mode=kuscia --serving_config_file=/etc/kuscia/serving-config.conf
        configVolumeMounts:
        - mountPath: /etc/kuscia/serving-config.conf
          subPath: serving-config.conf
        name: secretflow
        ports:
        - name: service
          port: 53508
          protocol: HTTP
          scope: Domain
        - name: communication
          port: 53509
          protocol: HTTP
          scope: Cluster
        - name: internal
          port: 53510
          protocol: HTTP
          scope: Domain
        - name: brpc-builtin
          port: 53511
          protocol: HTTP
          scope: Domain
        readinessProbe:
          httpGet:
            path: /health
            port: brpc-builtin
        livenessProbe:
          httpGet:
            path: /health
            port: brpc-builtin
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: brpc-builtin
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        workingDir: /root/sf_serving
  image:
    name: secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/serving-anolis8
    tag: 0.3.1b0
```
